[package]
name = "hello_world"
version = "0.1.0"
edition = "2024_07"

# See more keys and their definitions at https://docs.swmansion.com/scarb/docs/reference/manifest.html


[dev-dependencies]
cairo_test = "2.11.4"

[dependencies]
cairo_execute = "2.11.4"
alexandria_math = "0.5.2"

[cairo]
enable-gas = false

[executable]
